/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plane.glb --transform --types --resolution 4096 
Files: plane.glb [192.57MB] > X:\fiber-photo-mode\example\plane-transformed.glb [21.35MB] (89%)
Author: Azad Balabanian (https://sketchfab.com/azadbal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plane-crash-by-a-brothel-in-nevada-9931703442a14a3db2cd53c368706c64
Title: Plane Crash by a Brothel in Nevada
*/

import { useGLTF } from "@react-three/drei";
import { useLayoutEffect } from "react";
import * as THREE from "three";
import type { GLTF } from "three/examples/jsm/Addons.js";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
  };
  materials: {
    Crash_plane_brothel_Material_u1_v1: THREE.MeshBasicMaterial;
    Crash_plane_brothel_Material_u1_v2: THREE.MeshBasicMaterial;
    Crash_plane_brothel_Material_u1_v3: THREE.MeshBasicMaterial;
    Crash_plane_brothel_Material_u2_v1: THREE.MeshBasicMaterial;
    Crash_plane_brothel_Material_u2_v2: THREE.MeshBasicMaterial;
    Crash_plane_brothel_Material_u2_v3: THREE.MeshBasicMaterial;
    Crash_plane_brothel_Material_u3_v1: THREE.MeshBasicMaterial;
    Crash_plane_brothel_Material_u3_v2: THREE.MeshBasicMaterial;
  };
};

export function Plane() {
  const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}plane.glb`) as any as GLTFResult;

  useLayoutEffect(() => {
    Object.values(materials).forEach((mat: any) => {
      const newMat = new THREE.MeshStandardMaterial({
        map: mat.map,
      });
      mat.dispose();
      Object.assign(mat, newMat);
    });
  }, [materials]);

  return (
    <group dispose={null} position={[0, -0.5, 0]}>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Crash_plane_brothel_Material_u1_v1}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_3.geometry}
        material={materials.Crash_plane_brothel_Material_u1_v2}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Crash_plane_brothel_Material_u1_v3}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Crash_plane_brothel_Material_u2_v1}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Crash_plane_brothel_Material_u2_v2}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Crash_plane_brothel_Material_u2_v3}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Crash_plane_brothel_Material_u3_v1}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Crash_plane_brothel_Material_u3_v2}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}plane.glb`);
